CREATE TABLE IF NOT EXISTS garages(owner_id TEXT PRIMARY KEY,records TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS shares(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL REFERENCES garages(owner_id),title TEXT NOT NULL,selected_ids TEXT NOT NULL,include_codes INTEGER NOT NULL DEFAULT 0,include_photos INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL,discord_status TEXT NOT NULL DEFAULT 'not_configured',next_attempt DOUBLE PRECISION NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS idx_shares_owner ON shares(owner_id);
CREATE TABLE IF NOT EXISTS mail_outbox(id TEXT PRIMARY KEY,payload TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),expires_at TIMESTAMPTZ NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,next_attempt TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS auth_throttle(key TEXT PRIMARY KEY,count INTEGER NOT NULL,expires_at TIMESTAMPTZ NOT NULL);

CREATE TABLE IF NOT EXISTS auth_verification_uses(hash TEXT PRIMARY KEY,expires_at TIMESTAMPTZ NOT NULL);
